/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolyalpha;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author 850110
 */
public class Card extends javax.swing.JFrame {

    /**
     * Creates new form Card
     */
    String title, price, baseRent,rent1, rent2, rent3,rentHotel,mortgage, house, hotel;
    Color background;
    ImageIcon ic;
    public Card(Color bg, ImageIcon icon, int index, String theme) {
        this.background= bg;
        this.ic= icon;
        Properties_Data p = new Properties_Data(theme);
        p.GetProp();
        title = p.prop[index].name;
        price = "Price $"+ p.prop[index].price;
        baseRent = "RENT $"+p.prop[index].rent1;
        rent1 = "With 1 House $"+p.prop[index].rent2;
        rent2 = "With 2 House $"+p.prop[index].rent3;
        rent3 = "With 3 House $"+p.prop[index].rent4;
        rentHotel = "With Hotel $"+p.prop[index].rentH;
        mortgage = "Mortgage value $"+p.prop[index].price/2;
        house = "Houses cost $"+p.prop[index].priceHouse;
        house = "Hotel costs $"+((p.prop[index].priceHouse*1.5)+50);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel(title);
        lblDeed = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblRent = new javax.swing.JLabel();
        lblRent1 = new javax.swing.JLabel(baseRent);
        lblRent2 = new javax.swing.JLabel();
        lblRent3 = new javax.swing.JLabel();
        lblRent4 = new javax.swing.JLabel();
        lblRent5 = new javax.swing.JLabel();
        lblRent6 = new javax.swing.JLabel();
        lblRent7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(background);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 30));

        lblDeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeed.setText("Title Deed");
        jPanel2.add(lblDeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 215, -1));
        jPanel2.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        lblRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRent.setText(hotel);
        jPanel2.add(lblRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 30));

        lblRent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblRent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 30));

        lblRent2.setText(rent1);
        jPanel2.add(lblRent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 30));

        lblRent3.setText(rent2);
        jPanel2.add(lblRent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 30));

        lblRent4.setText(rent3);
        jPanel2.add(lblRent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 30));

        lblRent5.setText(rentHotel);
        jPanel2.add(lblRent5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 30));

        lblRent6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRent6.setText(mortgage);
        jPanel2.add(lblRent6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 30));

        lblRent7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRent7.setText(house);
        jPanel2.add(lblRent7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 240, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 324);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Card().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDeed;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblRent;
    private javax.swing.JLabel lblRent1;
    private javax.swing.JLabel lblRent2;
    private javax.swing.JLabel lblRent3;
    private javax.swing.JLabel lblRent4;
    private javax.swing.JLabel lblRent5;
    private javax.swing.JLabel lblRent6;
    private javax.swing.JLabel lblRent7;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
