/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolyalpha;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import javax.swing.border.LineBorder;

/**
 *
 * @author Harsh
 */
public class GameOver extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    int counter = 0;
    Timer t;
    Board board;
    int index = 0;   
    int players = 4;
    int moneys[] = new int[4];
    public GameOver(/*Board bd*/) {
//        this.board = bd;
        initComponents();
        moneys[0]=500;
        moneys[1]=1000;
        moneys[2]=2000;
        moneys[3]=3000;   
        AddProgressBars(moneys[0]);
             
    }
   
    public void AddProgressBars(int upperLimit) {
        final int u = upperLimit;
        JPanel pane = new JPanel(new BorderLayout());        
        final JProgressBar prog = new JProgressBar(JProgressBar.VERTICAL, 0, upperLimit);
        prog.setPreferredSize(new Dimension(20, 260));
        prog.setValue(counter);
        final JLabel lblMoney = new JLabel(String.valueOf(u));
        lblMoney.setFont(new Font("Showcard Gothic", 0, 36));
        JLabel player = new JLabel("PLAYER "+String.valueOf(index+1));
        player.setFont(new Font("Showcard Gothic", 0, 18));        
        pane.add(player, BorderLayout.NORTH);
        pane.add(prog, BorderLayout.WEST);
        pane.add(lblMoney, BorderLayout.EAST);
        pane.setBorder(new LineBorder(Color.BLACK, 2));
        paneScore.add(pane);
        paneScore.setPreferredSize(pane.getSize());
        t = new Timer(2, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                final int c = counter;
                if (counter == u) {
                    t.stop();
                    counter=0;
                    index++;
                    if(index <players){
                        AddProgressBars(moneys[index]);
                    }
                }
//                System.out.println(c);
                lblMoney.setText(String.valueOf(c));
                prog.setValue(c);
                paneScore.repaint();
                counter++;
            }
        });
        t.start();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneScore = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GAME OVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneScore, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel paneScore;
    // End of variables declaration//GEN-END:variables
}
