/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolyalpha;

/**
 *
 * @author HaardTrivedi
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnObject = new javax.swing.JButton();
        btnPrep = new javax.swing.JButton();
        btnBank = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        btnRent = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnBuyProp = new javax.swing.JButton();
        btnChaComm = new javax.swing.JButton();
        btnTax = new javax.swing.JButton();
        btnEGS = new javax.swing.JButton();
        btnCar = new javax.swing.JButton();
        btnJail = new javax.swing.JButton();
        btnHouse = new javax.swing.JButton();
        btnHotel = new javax.swing.JButton();
        btnTrade = new javax.swing.JButton();
        btnMortgage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Help");
        lblTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 0, 477, 76);

        btnObject.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnObject.setText("oBJECT");
        btnObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjectActionPerformed(evt);
            }
        });
        getContentPane().add(btnObject);
        btnObject.setBounds(26, 82, 207, 25);

        btnPrep.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnPrep.setText("Preparation");
        btnPrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrep);
        btnPrep.setBounds(26, 118, 207, 25);

        btnBank.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnBank.setText("The Bank");
        btnBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankActionPerformed(evt);
            }
        });
        getContentPane().add(btnBank);
        btnBank.setBounds(26, 154, 207, 25);

        btnGo.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGo);
        btnGo.setBounds(26, 190, 207, 25);

        btnRent.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnRent.setText("Paying Rent");
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });
        getContentPane().add(btnRent);
        btnRent.setBounds(26, 226, 207, 25);

        btnPlay.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnPlay.setText("Equipment");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay);
        btnPlay.setBounds(26, 262, 207, 25);

        btnBuyProp.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnBuyProp.setText("Buying Property");
        btnBuyProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyPropActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuyProp);
        btnBuyProp.setBounds(26, 295, 207, 25);

        btnChaComm.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnChaComm.setText("Chance and Community Chest");
        btnChaComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChaCommActionPerformed(evt);
            }
        });
        getContentPane().add(btnChaComm);
        btnChaComm.setBounds(26, 331, 207, 25);

        btnTax.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnTax.setText("Tax");
        btnTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxActionPerformed(evt);
            }
        });
        getContentPane().add(btnTax);
        btnTax.setBounds(251, 82, 210, 25);

        btnEGS.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnEGS.setText("End Game Scenario");
        btnEGS.setToolTipText("");
        btnEGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEGSActionPerformed(evt);
            }
        });
        getContentPane().add(btnEGS);
        btnEGS.setBounds(251, 331, 210, 25);

        btnCar.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnCar.setText("Car insurance");
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCar);
        btnCar.setBounds(251, 118, 210, 25);

        btnJail.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnJail.setText("Jail & Go to Jail");
        btnJail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJailActionPerformed(evt);
            }
        });
        getContentPane().add(btnJail);
        btnJail.setBounds(251, 154, 210, 25);

        btnHouse.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnHouse.setText("House");
        btnHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHouseActionPerformed(evt);
            }
        });
        getContentPane().add(btnHouse);
        btnHouse.setBounds(251, 190, 210, 25);

        btnHotel.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnHotel.setText("Hotel");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnHotel);
        btnHotel.setBounds(251, 226, 210, 25);

        btnTrade.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnTrade.setText("Trading");
        btnTrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrade);
        btnTrade.setBounds(251, 262, 210, 25);

        btnMortgage.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        btnMortgage.setText("Mortgage");
        btnMortgage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMortgageActionPerformed(evt);
            }
        });
        getContentPane().add(btnMortgage);
        btnMortgage.setBounds(251, 295, 210, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObjectActionPerformed

    private void btnPrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrepActionPerformed

    private void btnBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBankActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRentActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnBuyPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyPropActionPerformed

    private void btnChaCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChaCommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChaCommActionPerformed

    private void btnTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaxActionPerformed

    private void btnEGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEGSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEGSActionPerformed

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarActionPerformed

    private void btnJailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJailActionPerformed

    private void btnHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHouseActionPerformed

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHotelActionPerformed

    private void btnTradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTradeActionPerformed

    private void btnMortgageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMortgageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMortgageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBank;
    private javax.swing.JButton btnBuyProp;
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnChaComm;
    private javax.swing.JButton btnEGS;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnHotel;
    private javax.swing.JButton btnHouse;
    private javax.swing.JButton btnJail;
    private javax.swing.JButton btnMortgage;
    private javax.swing.JButton btnObject;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPrep;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnTax;
    private javax.swing.JButton btnTrade;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
