/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolyalpha;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;

/**
 *
 * @author 714449
 */
public class StartScreenfrm extends javax.swing.JFrame {

    /**
     * Creates new form StartScreenfrm
     */
    public int w, h;
    public ImageIcon bkpc = new ImageIcon("src/monopolyalpha/bkpc.png"); //school pc size
    public ImageIcon bkdesk = new ImageIcon("src/monopolyalpha/bkdesk.png"); //lcd desktop0
    public ImageIcon bklap = new ImageIcon("src/monopolyalpha/bklap.png"); //normal none wide laptop size
    public ImageIcon bklapwide = new ImageIcon("src/monopolyalpha/bklapwide.png");//wide laps
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    public StartScreenfrm() {
        initComponents();

        this.setExtendedState(MAXIMIZED_BOTH);
        w = (int) screenSize.getWidth();
        h = (int) screenSize.getHeight();
        bk.setSize(w, h);
        bkpanel.setSize(w, h);
        System.out.println(w + "" + h);
        backset(w, h);
    }

    public void backset(int w, int h) {
        if (w == 1024 && h == 768) {
//            bk.setSize(w, h);
            bk.setIcon(bkpc);
        } else if (w == 1280 && h == 768) {
//            bk.setSize(w, h);
            bk.setIcon(bkdesk);
        } else if (w == 1280 && h == 1024) {
//            bk.setSize(w, h);
            bk.setIcon(bklap);
        } else if (w == 1366 && h == 768) {
            bk.setIcon(bklapwide);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkpanel = new javax.swing.JPanel();
        btnNewGame = new javax.swing.JButton();
        btnLoadGame = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        bkpanel.setOpaque(false);

        btnNewGame.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnNewGame.setIcon(new ImageIcon("Icons/Miscellaneous/buttons/green/green 1.png"));
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnLoadGame.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnLoadGame.setIcon(new ImageIcon("Icons/Miscellaneous/buttons/green/green 2.png"));
        btnLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });

        btnHelp.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnHelp.setIcon(new ImageIcon("Icons/Miscellaneous/buttons/green/green 3.png"));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnAbout.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnAbout.setIcon(new ImageIcon("Icons/Miscellaneous/buttons/green/green 4.png"));
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnExit.setIcon(new ImageIcon("Icons/Miscellaneous/buttons/green/green 5.png"));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkpanelLayout = new javax.swing.GroupLayout(bkpanel);
        bkpanel.setLayout(bkpanelLayout);
        bkpanelLayout.setHorizontalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkpanelLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        bkpanelLayout.setVerticalGroup(
            bkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkpanelLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(bkpanel);
        bkpanel.setBounds(0, 0, 790, 760);

        bk.setLabelFor(bk);
        bk.setMaximumSize(new java.awt.Dimension(1900, 1900));
        bk.setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().add(bk);
        bk.setBounds(0, 0, 1024, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadGameActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Save_Manager().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnLoadGameActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemeSelect().setVisible(true);
            }
        });

    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutFrame().setVisible(true);
            }
        });
        //////NICE TRY AYY LMAO
//        JDialog about = new JDialog();
//        JLayeredPane jp = new JLayeredPane();
//        jp.setBounds(this.getBounds());
//        jp.setLayout(null);
//        jp.setBackground(Color.yellow);
//        JLabel ab = new JLabel("<html>About text goes here:<br>"
//                + "AND HERE I AM TRYING TO CODE ASDINTAS<br>"
//                + "SEND HELP<br>"
//                + "THE ABOUT ENDS HERE", JLabel.CENTER);
//        JLabel ico1 = new JLabel(new ImageIcon("Icons/Dice/Generic/Dice 1.png"));
//        JLabel ico2 = new JLabel(new ImageIcon("Icons/Dice/Maple/Dice 1.png"));
//        JLabel ico3 = new JLabel(new ImageIcon("Icons/Dice/Superhero/Dice 1.png"));
//        JLabel bg = new JLabel(new ImageIcon("C:\\Users\\Harsh\\Documents\\Monopoly Proj\\green pattern.png"));
//        jp.add(ico1, 2);
//        jp.add(ico2, 2);
//        jp.add(ico3, 2);
//        jp.add(ab, 2);
//        jp.add(bg,1);
////        about.add(ico1, BorderLayout.LINE_START);
////        about.add(ico2, BorderLayout.NORTH);
////        about.add(ico3, BorderLayout.LINE_END);      
////        about.add(ab, BorderLayout.SOUTH);
//        
//        about.add(jp);
//        about.setSize(w, h);
//        about.setUndecorated(true);
//        about.pack();
//        about.setLocationRelativeTo(null);
//        about.setVisible(true);


    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreenfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreenfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreenfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreenfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreenfrm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bk;
    private javax.swing.JPanel bkpanel;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    // End of variables declaration//GEN-END:variables
}
