/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolyalpha;

import java.awt.Checkbox;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Harsh
 */
public class TradeForm extends javax.swing.JFrame {

    /**
     * Creates new form TradeForm
     */
    Checkbox[] checkboxes1, checkboxes2;
    Board board = InitTest.board;
    JPanel[] others;

    public TradeForm() {
        initComponents();
//        jPanel1.setPreferredSize(new Dimension(200, jPanel1.getHeight()));
        paneCur.setLayout(new BoxLayout(paneCur, BoxLayout.Y_AXIS));
        checkboxes1 = new Checkbox[36];
        checkboxes2 = new Checkbox[36];
        others = new JPanel[board.players];
        for (int i = 0; i < others.length; i++) {
            if (i != board.turn) {
                others[i] = new JPanel();
                others[i].setLayout(new BoxLayout(others[i], BoxLayout.Y_AXIS));
                others[i].setBorder(new LineBorder(board.colorPalette[i], 3));
                others[i].setSize(paneOthers.getSize());
                for (int j = 0; j < board.propName.length; j++) {
                    if (board.propOwner[j] == i) {
                        checkboxes2[j] = new Checkbox(board.propName[j]);
                        checkboxes2[j].setFont(new Font("Showcard Gothic", 0, 18));
                        others[i].add(checkboxes2[j]);
                        paneOthers.addTab(board.name[i], others[i]);
                        paneCur.validate();
                        paneCur.repaint();
                    }
                }
            }

        }
        for (int i = 0; i < board.propName.length; i++) {
            if (board.propOwner[i] == board.turn) {
                System.out.println(board.propName[i] + " added");
                checkboxes1[i] = new Checkbox(board.propName[i]);
                checkboxes1[i].setFont(new Font("Showcard Gothic", 0, 18));
                paneCur.add(checkboxes1[i]);
                paneCur.validate();
                paneCur.repaint();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paneCur = new javax.swing.JPanel();
        paneOthers = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Monopoly Trade Terminal");

        paneCur.setBorder(javax.swing.BorderFactory.createLineBorder(board.colorPalette[board.turn], 3));

        javax.swing.GroupLayout paneCurLayout = new javax.swing.GroupLayout(paneCur);
        paneCur.setLayout(paneCurLayout);
        paneCurLayout.setHorizontalGroup(
            paneCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        paneCurLayout.setVerticalGroup(
            paneCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(paneCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(paneOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneCur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneOthers, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TradeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel paneCur;
    private javax.swing.JTabbedPane paneOthers;
    // End of variables declaration//GEN-END:variables
}
