/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopolyalpha;

import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Harsh
 */
public class TradeForm extends javax.swing.JFrame {

    /**
     * Creates new form TradeForm
     */
    public JCheckBox[] checkboxes1, checkboxes2;
    Board board = InitTest.board;
    JPanel[] others;
    ArrayList<Integer> from = new ArrayList();
    ArrayList<Integer> to = new ArrayList();

    public TradeForm() {
        initComponents();
        paneCur.setPreferredSize(new Dimension(paneCur.getWidth(), paneOthers.getHeight()));
        paneCur.setLayout(new BoxLayout(paneCur, BoxLayout.Y_AXIS));
        checkboxes1 = new JCheckBox[36];
        checkboxes2 = new JCheckBox[36];
        others = new JPanel[board.players];
        for (int i = 0; i < others.length; i++) {
            if (i != board.turn) {
                others[i] = new JPanel();
                others[i].setLayout(new BoxLayout(others[i], BoxLayout.Y_AXIS));
                others[i].setBorder(new LineBorder(board.colorPalette[i], 3));
                others[i].setBackground(board.colorPalette[i].brighter());
                others[i].setSize(paneOthers.getSize());
                for (int j = 0; j < board.propName.length; j++) {
                    if (board.propOwner[j] == i) {
                        this.checkboxes2[j] = new JCheckBox(board.propName[j]);
                        this.checkboxes2[j].setFont(new Font("Showcard Gothic", 0, 18));
                        this.checkboxes2[j].setOpaque(false);
                        others[i].add(checkboxes2[j]);
                        paneOthers.addTab(board.name[i], others[i]);
                        paneCur.validate();
                        paneCur.repaint();
                    }
                }
            }

        }
        for (int i = 0; i < board.propName.length; i++) {
            if (board.propOwner[i] == board.turn) {
                System.out.println(board.propName[i] + " added");
                this.checkboxes1[i] = new JCheckBox(board.propName[i]);
                this.checkboxes1[i].setFont(new Font("Showcard Gothic", 0, 18));
                this.checkboxes1[i].setOpaque(false);
                paneCur.add(checkboxes1[i]);
                paneCur.validate();
                paneCur.repaint();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paneCur = new javax.swing.JPanel();
        paneOthers = new javax.swing.JTabbedPane();
        btnTrd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Monopoly Trade Terminal");

        paneCur.setBorder(javax.swing.BorderFactory.createLineBorder(board.colorPalette[board.turn], 3));

        javax.swing.GroupLayout paneCurLayout = new javax.swing.GroupLayout(paneCur);
        paneCur.setLayout(paneCurLayout);
        paneCurLayout.setHorizontalGroup(
            paneCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        paneCurLayout.setVerticalGroup(
            paneCurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnTrd.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        btnTrd.setText("TRADE");
        btnTrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(paneCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(paneOthers, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneCur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneOthers))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(btnTrd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrdActionPerformed
        // TODO add your handling code here:
        int tradeFrom = board.turn;
        int tradeToInd = paneOthers.getSelectedIndex();
        int tradeTo = -1;
        for (int i = 0; i < others.length; i++) {
            if (paneOthers.getTitleAt(tradeToInd).equals(board.name[i])) {
                System.out.println("other player found");
                tradeTo = i;
            }
        }
        for (int i = 0; i < checkboxes1.length; i++) {
            if (checkboxes1[i] != null) {
                System.out.println("From prop: " + checkboxes1[i].getText());
                if (checkboxes1[i].isSelected()) {
                    from.add(i);
                }
            }
        }
        for (int i = 0; i < checkboxes2.length; i++) {
            if (checkboxes2[i] != null) {
                System.out.println("To prop: " + checkboxes2[i].getText());
                if (checkboxes2[i].isSelected()) {
                    to.add(i);
                }
            }
        }
        for (int i = 0; i < from.size(); i++) {
            System.out.println("from: " + from.get(i));
            board.propOwner[from.get(i)] = tradeTo;
            board.updateColors(tradeTo, from.get(i));
        }
        for (int i = 0; i < to.size(); i++) {
            System.out.println("to: " + to.get(i));
            board.propOwner[to.get(i)] = tradeFrom;
            board.updateColors(tradeFrom, to.get(i));
        }

    }//GEN-LAST:event_btnTrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TradeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel paneCur;
    private javax.swing.JTabbedPane paneOthers;
    // End of variables declaration//GEN-END:variables
}
